"""Añadir tabla Configuracion para parámetros del sistema

Revision ID: 07ba38127eb4
Revises: 1c9ed3962cf0
Create Date: 2025-11-02 17:03:17.500932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07ba38127eb4'
down_revision = '1c9ed3962cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion',
    sa.Column('nombre_parametro', sa.String(length=100), nullable=False),
    sa.Column('valor_parametro', sa.String(length=100), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nombre_parametro')
    )
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.alter_column('total_monto',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('monto_preaviso',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_cesantia',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_vacaciones',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_aguinaldo',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('monto_salario_pendiente',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.alter_column('monto_salario_pendiente',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_aguinaldo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_vacaciones',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_cesantia',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('monto_preaviso',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_monto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    op.drop_table('configuracion')
    # ### end Alembic commands ###
