"""Schema Inicial

Revision ID: 0d9bca41edf3
Revises: 
Create Date: 2025-08-27 16:56:03.509175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9bca41edf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriado',
    sa.Column('id_feriado', sa.Integer(), nullable=False),
    sa.Column('fecha_feriado', sa.Date(), nullable=False),
    sa.Column('descripcion_feriado', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_feriado'),
    sa.UniqueConstraint('fecha_feriado')
    )
    op.create_table('puesto',
    sa.Column('id_puesto', sa.Integer(), nullable=False),
    sa.Column('tipo_puesto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_puesto'),
    sa.UniqueConstraint('tipo_puesto')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('tipo_rol', sa.String(length=100), nullable=False),
    sa.Column('descripcion_rol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('tipo_rol')
    )
    op.create_table('tipo_ap',
    sa.Column('id_tipo_ap', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_ap'),
    sa.UniqueConstraint('nombre_tipo')
    )
    op.create_table('tipo_nomina',
    sa.Column('id_tipo_nomina', sa.Integer(), nullable=False),
    sa.Column('nombre_tipo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_nomina'),
    sa.UniqueConstraint('nombre_tipo')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('estado_usuario', sa.Boolean(), nullable=False),
    sa.Column('Rol_id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Rol_id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('username')
    )
    op.create_table('empleado',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_primero', sa.String(length=100), nullable=False),
    sa.Column('apellido_segundo', sa.String(length=100), nullable=True),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('salario_base', sa.Float(), nullable=False),
    sa.Column('fecha_salida', sa.Date(), nullable=True),
    sa.Column('estado_empleado', sa.Boolean(), nullable=False),
    sa.Column('Puesto_id_puesto', sa.Integer(), nullable=False),
    sa.Column('Usuario_id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Puesto_id_puesto'], ['puesto.id_puesto'], ),
    sa.ForeignKeyConstraint(['Usuario_id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_empleado'),
    sa.UniqueConstraint('Usuario_id_usuario'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('accion_personal',
    sa.Column('id_accion', sa.Integer(), nullable=False),
    sa.Column('fecha_accion', sa.Date(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.Column('Tipo_AP_id_tipo_ap', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['Tipo_AP_id_tipo_ap'], ['tipo_ap.id_tipo_ap'], ),
    sa.PrimaryKeyConstraint('id_accion')
    )
    op.create_table('aguinaldo',
    sa.Column('id_aguinaldo', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id_aguinaldo')
    )
    op.create_table('nomina',
    sa.Column('id_nomina', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('salario_bruto', sa.Float(), nullable=False),
    sa.Column('salario_neto', sa.Float(), nullable=False),
    sa.Column('deducciones', sa.Float(), nullable=False),
    sa.Column('estado_pago', sa.String(length=50), nullable=False),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id_nomina')
    )
    op.create_table('historico_nomina',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('fecha_historial', sa.Date(), nullable=False),
    sa.Column('Nomina_id_nomina', sa.Integer(), nullable=False),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.Column('salario_bruto', sa.Float(), nullable=False),
    sa.Column('salario_neto', sa.Float(), nullable=False),
    sa.Column('deducciones', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['Nomina_id_nomina'], ['nomina.id_nomina'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_table('registro_asistencia',
    sa.Column('id_registro_asistencia', sa.Integer(), nullable=False),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('hora_nominal', sa.Float(), nullable=True),
    sa.Column('hora_extra', sa.Float(), nullable=True),
    sa.Column('hora_feriado', sa.Float(), nullable=True),
    sa.Column('estado_feriado', sa.Boolean(), nullable=False),
    sa.Column('aprobacion_registro', sa.Boolean(), nullable=False),
    sa.Column('Nomina_id_nomina', sa.Integer(), nullable=True),
    sa.Column('Feriado_id_feriado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.ForeignKeyConstraint(['Feriado_id_feriado'], ['feriado.id_feriado'], ),
    sa.ForeignKeyConstraint(['Nomina_id_nomina'], ['nomina.id_nomina'], ),
    sa.PrimaryKeyConstraint('id_registro_asistencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_asistencia')
    op.drop_table('historico_nomina')
    op.drop_table('nomina')
    op.drop_table('aguinaldo')
    op.drop_table('accion_personal')
    op.drop_table('empleado')
    op.drop_table('usuario')
    op.drop_table('tipo_nomina')
    op.drop_table('tipo_ap')
    op.drop_table('rol')
    op.drop_table('puesto')
    op.drop_table('feriado')
    # ### end Alembic commands ###
