"""Agregar tabla concepto_nomina para incapacidades y vacaciones

Revision ID: 19ff7c3d198c
Revises: bbb9d8746cf2
Create Date: 2026-04-25 17:00:24.693374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ff7c3d198c'
down_revision = 'bbb9d8746cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto_nomina',
    sa.Column('id_concepto', sa.Integer(), nullable=False),
    sa.Column('Nomina_id_nomina', sa.Integer(), nullable=False),
    sa.Column('tipo_concepto', sa.String(length=50), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['Nomina_id_nomina'], ['nomina.id_nomina'], ),
    sa.PrimaryKeyConstraint('id_concepto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concepto_nomina')
    # ### end Alembic commands ###
