"""Agrega monto_salario_pendiente a Liquidacion

Revision ID: 1c9ed3962cf0
Revises: 3e3f98adfff6
Create Date: 2025-09-25 11:03:03.199549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9ed3962cf0'
down_revision = '3e3f98adfff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_salario_pendiente', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidacion', schema=None) as batch_op:
        batch_op.drop_column('monto_salario_pendiente')

    # ### end Alembic commands ###
