"""Añadir campo es_pago_obligatorio a feriado

Revision ID: 221dcb4cbdf1
Revises: 
Create Date: 2025-08-29 17:30:45.048510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '221dcb4cbdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feriado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_obligatorio', sa.Boolean(), nullable=False))

    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_obligatorio', sa.Boolean(), nullable=False))
        batch_op.drop_column('estado_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_pago', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('pago_obligatorio')

    with op.batch_alter_table('feriado', schema=None) as batch_op:
        batch_op.drop_column('pago_obligatorio')

    # ### end Alembic commands ###
