"""Añadiendo la columna id_accion_personal a la tabla accion_personal

Revision ID: 27dc80404f69
Revises: 
Create Date: 2025-09-03 17:44:18.333388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27dc80404f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accion_personal', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tipo_ap', ['Tipo_Ap_id_tipo_ap'], ['id_tipo_ap'])
        batch_op.drop_column('id_accion_personal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accion_personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_accion_personal', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
