"""actualizon de modelo para permisos

Revision ID: 292dc20912b6
Revises: 3bdc519cfd82
Create Date: 2025-09-10 10:33:14.306821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292dc20912b6'
down_revision = '3bdc519cfd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_permiso')
    op.drop_table('permiso')
    # ### end Alembic commands ###
