"""Añadió campo de cambio de contraseña requerido

Revision ID: 3bdc519cfd82
Revises: 9887490df8c3
Create Date: 2025-09-08 17:32:10.446678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bdc519cfd82'
down_revision = '9887490df8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cambio_password_requerido', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('cambio_password_requerido')

    # ### end Alembic commands ###
