"""Creación de tabla Liquidacion

Revision ID: 3e3f98adfff6
Revises: 70e7178b5282
Create Date: 2025-09-25 09:52:11.880812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3f98adfff6'
down_revision = '70e7178b5282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidacion',
    sa.Column('id_liquidacion', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('fecha_fin_contrato', sa.Date(), nullable=False),
    sa.Column('total_monto', sa.Float(), nullable=False),
    sa.Column('monto_preaviso', sa.Float(), nullable=True),
    sa.Column('monto_cesantia', sa.Float(), nullable=True),
    sa.Column('monto_vacaciones', sa.Float(), nullable=True),
    sa.Column('monto_aguinaldo', sa.Float(), nullable=True),
    sa.Column('Empleado_id_empleado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], ),
    sa.PrimaryKeyConstraint('id_liquidacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liquidacion')
    # ### end Alembic commands ###
