"""Corregir el nombre de la clave foránea en nomina

Revision ID: 5175da73f64f
Revises: f48c133f08f4
Create Date: 2025-08-28 11:17:43.341583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5175da73f64f'
down_revision = 'f48c133f08f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TipoNomina_id_tipo_nomina', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('nomina_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_nomina', ['TipoNomina_id_tipo_nomina'], ['id_tipo_nomina'])
        batch_op.drop_column('id_tipo_nomina')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tipo_nomina', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('nomina_ibfk_2'), 'tipo_nomina', ['id_tipo_nomina'], ['id_tipo_nomina'])
        batch_op.drop_column('TipoNomina_id_tipo_nomina')

    # ### end Alembic commands ###
