"""Add lunch break fields to RegistroAsistencia

Revision ID: 70e7178b5282
Revises: 292dc20912b6
Create Date: 2025-09-22 19:07:50.700842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e7178b5282'
down_revision = '292dc20912b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_salida_almuerzo', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hora_entrada_almuerzo', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_asistencia', schema=None) as batch_op:
        batch_op.drop_column('hora_entrada_almuerzo')
        batch_op.drop_column('hora_salida_almuerzo')

    # ### end Alembic commands ###
