"""Añadio campos a usuario para vacaciones e intentos fallidos 

Revision ID: 9887490df8c3
Revises: fe1102f60018
Create Date: 2025-09-08 16:36:13.851099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9887490df8c3'
down_revision = 'fe1102f60018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacaciones_disponibles', sa.Integer(), nullable=False))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('vacaciones_disponibles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vacaciones_disponibles', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_column('vacaciones_disponibles')

    # ### end Alembic commands ###
