"""actualizacion de modelo de accion de personal

Revision ID: a28d588ec5de
Revises: c6c8cc55ef1b
Create Date: 2025-09-02 17:23:33.161298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a28d588ec5de'
down_revision = 'c6c8cc55ef1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_nomina')
    with op.batch_alter_table('tipo_nomina', schema=None) as batch_op:
        batch_op.alter_column('nombre_tipo',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('nombre_tipo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_nomina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nombre_tipo'), ['nombre_tipo'], unique=True)
        batch_op.alter_column('nombre_tipo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    op.create_table('historico_nomina',
    sa.Column('id_historico', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha_historial', sa.DATE(), nullable=False),
    sa.Column('Nomina_id_nomina', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Empleado_id_empleado', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salario_bruto', mysql.FLOAT(), nullable=False),
    sa.Column('salario_neto', mysql.FLOAT(), nullable=False),
    sa.Column('deducciones', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['Empleado_id_empleado'], ['empleado.id_empleado'], name=op.f('historico_nomina_ibfk_1')),
    sa.ForeignKeyConstraint(['Nomina_id_nomina'], ['nomina.id_nomina'], name=op.f('historico_nomina_ibfk_2')),
    sa.PrimaryKeyConstraint('id_historico'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
