"""Agregar tabla deduccion para deducciones detalladas

Revision ID: bbb9d8746cf2
Revises: 060c15b1750e
Create Date: 2026-04-25 16:11:32.752260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb9d8746cf2'
down_revision = '060c15b1750e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deduccion',
    sa.Column('id_deduccion', sa.Integer(), nullable=False),
    sa.Column('Nomina_id_nomina', sa.Integer(), nullable=False),
    sa.Column('tipo_deduccion', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['Nomina_id_nomina'], ['nomina.id_nomina'], ),
    sa.PrimaryKeyConstraint('id_deduccion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deduccion')
    # ### end Alembic commands ###
