"""Cambiar tipo de dato de total_horas y hora_nominal a Float

Revision ID: c3066301f1ef
Revises: 221dcb4cbdf1
Create Date: 2025-08-31 20:54:32.203606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3066301f1ef'
down_revision = '221dcb4cbdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_horas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monto_pago', sa.Float(), nullable=True))
        batch_op.drop_column('estado_feriado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_asistencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_feriado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('monto_pago')
        batch_op.drop_column('total_horas')

    # ### end Alembic commands ###
