"""Mensaje descriptivo de los cambios

Revision ID: d82467b4b037
Revises: 0d9bca41edf3
Create Date: 2025-08-28 10:57:20.269268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82467b4b037'
down_revision = '0d9bca41edf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_nomina_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tipo_nomina', ['tipo_nomina_id'], ['id_tipo_nomina'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_nomina_id')

    # ### end Alembic commands ###
