"""Añadiendo columna de tipo de acción (nueva migración)

Revision ID: e6317c02c3e9
Revises: 43ed78e55ea7
Create Date: 2025-09-02 17:40:30.252385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6317c02c3e9'
down_revision = '43ed78e55ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accion_personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Tipo_Ap_id_tipo_ap', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cantidad_dia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estado_ap', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_aprobador', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('documento_adjunto', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('accion_personal_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_ap', ['Tipo_Ap_id_tipo_ap'], ['id_tipo_ap'])
        batch_op.drop_column('Tipo_AP_id_tipo_ap')
        batch_op.drop_column('id_accion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accion_personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_accion', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('Tipo_AP_id_tipo_ap', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('accion_personal_ibfk_2'), 'tipo_ap', ['Tipo_AP_id_tipo_ap'], ['id_tipo_ap'])
        batch_op.drop_column('documento_adjunto')
        batch_op.drop_column('fecha_aprobacion')
        batch_op.drop_column('id_aprobador')
        batch_op.drop_column('estado_ap')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('cantidad_dia')
        batch_op.drop_column('Tipo_Ap_id_tipo_ap')

    # ### end Alembic commands ###
