"""Mensaje descriptivo de los cambios

Revision ID: f48c133f08f4
Revises: d82467b4b037
Create Date: 2025-08-28 11:11:19.169023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f48c133f08f4'
down_revision = 'd82467b4b037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tipo_nomina', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('nomina_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tipo_nomina', ['id_tipo_nomina'], ['id_tipo_nomina'])
        batch_op.drop_column('tipo_nomina_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nomina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_nomina_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('nomina_ibfk_2'), 'tipo_nomina', ['tipo_nomina_id'], ['id_tipo_nomina'])
        batch_op.drop_column('id_tipo_nomina')

    # ### end Alembic commands ###
