"""Añadio campos a usuario para vacaciones e intentos fallidos 

Revision ID: fe1102f60018
Revises: 27dc80404f69
Create Date: 2025-09-08 16:22:55.070672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1102f60018'
down_revision = '27dc80404f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intentos_fallidos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha_ultimo_intento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('vacaciones_disponibles', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('vacaciones_disponibles')
        batch_op.drop_column('fecha_ultimo_intento')
        batch_op.drop_column('intentos_fallidos')

    # ### end Alembic commands ###
